name: Reusable work flow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World

jobs:
  resuable-job:
    runs-on: Ubuntu-latest
    outputs:
      current-time: ${{steps.time.outputs.time}}
    steps:
      - name: Greet someone
        run: echo "Hello {{inputs..who-to-greet }}"
      - name: set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
